[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32dev

lib_deps =
    https://github.com/johnrickman/LiquidCrystal_I2C.git
    beegee-tokyo/DHT sensor library for ESPx
    madhephaestus/ESP32Servo
    knolleary/PubSubClient